[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "odict"
version = "1.9.1.dev0"
description = "Ordered Dictionary."
readme = "README.rst"
license = {text = "Python Software Foundation License"}
authors = [{name = "Node Contributors", email = "dev@conestack.org"}]
keywords = ["odict", "dict", "ordered", "dictionary", "mapping", "collection", "tree"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: Python Software Foundation License",
    "Operating System :: OS Independent",
    "Topic :: Software Development",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.10",
]

[project.urls]
Homepage = "https://github.com/conestack/odict"

[tool.hatch.build.targets.wheel]
packages = ["src/odict"]
[tool.zest-releaser]
create-wheel = true
